# Generated by Django 5.2.1 on 2025-05-12 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=50)),
                ('synopsis', models.TextField()),
                ('date_start', models.DateField(blank=True, null=True)),
                ('date_end', models.DateField(blank=True, null=True)),
                ('episode', models.IntegerField()),
                ('duration', models.IntegerField(help_text='Durée moyenne d’un épisode en minutes')),
                ('season', models.CharField(max_length=50)),
                ('studio', models.CharField(max_length=50)),
                ('format', models.CharField(max_length=50)),
                ('url_nautiljon', models.TextField()),
                ('url_mal', models.TextField()),
                ('genres', models.ManyToManyField(related_name='animes', to='collection.genre')),
                ('themes', models.ManyToManyField(related_name='animes', to='collection.theme')),
            ],
        ),
    ]
