# Generated by Django 5.2.1 on 2025-05-12 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_animeimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimeTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('language_code', models.CharField(max_length=2)),
                ('is_original', models.BooleanField(default=False)),
                ('is_nickname', models.BooleanField(default=False)),
                ('slug', models.CharField(max_length=255)),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='titles', to='collection.anime')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('anime', 'title', 'language_code'), name='unique_anime_title_language')],
            },
        ),
    ]
