# Generated by Django 5.2.1 on 2025-05-12 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0003_animetitle'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelationAnime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(max_length=100)),
                ('anime_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations_as_source', to='collection.anime')),
                ('anime_target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations_as_target', to='collection.anime')),
            ],
            options={
                'unique_together': {('anime_source', 'anime_target', 'relation_type')},
            },
        ),
    ]
