# Generated by Django 5.2.1 on 2025-05-12 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0004_relationanime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationanime',
            name='relation_type',
            field=models.CharField(choices=[('suite', 'Suite'), ('prequel', 'Préquelle'), ('spin-off', 'Spin-off'), ('remake', 'Remake'), ('histoire-supplémentaire', 'Histoire supplémentaire'), ('version-alternative', 'Version alternative'), ('compilation', 'Compilation'), ('parodie', 'Parodie'), ('pilote', 'Pilote')], max_length=50),
        ),
    ]
