# Generated by Django 5.2.1 on 2025-05-13 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0005_alter_relationanime_relation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='studio_3D',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='anime',
            name='format',
            field=models.CharField(choices=[('serie', 'Série'), ('oav', 'OAV'), ('film', 'Film'), ('special', 'Spécial'), ('musique', 'Musique'), ('animix-/-picture-drama', 'Animix / Picture drama'), ('court-metrage', 'Court-métrage'), ('publicité', 'Publicité'), ('inconnu', 'inconnu'), ('bonus', 'Bonus')], max_length=50),
        ),
        migrations.AlterField(
            model_name='anime',
            name='origin',
            field=models.CharField(choices=[('original', '\tŒuvre originale'), ('manga', 'Manga'), ('light-novel', 'Light Novel'), ('visual-novel', 'Visual Novel'), ('jeu-video', 'Jeu vidéo'), ('Jouets-/-figurines', 'Jouets / Figurines'), ('roman', 'Roman'), ('jeu-de-carte', 'Jeu de carte'), ('vocaloid', 'Vocaloid'), ('projet-transmedia', 'Projet transmédia'), ('autre', 'Autre'), ('anime', 'Anime'), ('doujinshi', 'Doujinshi'), ('film', 'Film'), ('chanson', 'Chanson'), ('vtuber', 'Vtuber')], max_length=50),
        ),
        migrations.AlterField(
            model_name='anime',
            name='studio',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='animetitle',
            name='language_code',
            field=models.CharField(choices=[('jp', 'jp'), ('en', 'en'), ('fr', 'fr'), ('ch', 'ch')], max_length=2),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='theme',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
