# Generated by Django 5.2.1 on 2025-05-13 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0006_anime_studio_3d_alter_anime_format_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='animetitle',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
    ]
