# Generated by Django 5.2.1 on 2025-05-13 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0007_animetitle_is_main'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animetitle',
            name='anime',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anime_titles', to='collection.anime'),
        ),
    ]
