# Generated by Django 5.2.1 on 2025-05-13 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0008_alter_animetitle_anime'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='main_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
