# Generated by Django 5.2.1 on 2025-05-13 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0009_anime_main_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='main_title',
            field=models.CharField(max_length=255),
        ),
    ]
