# Generated by Django 5.2.1 on 2025-05-13 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0010_alter_anime_main_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='studio_3D',
            field=models.CharField(max_length=150),
        ),
    ]
