# Generated by Django 5.2.1 on 2025-05-13 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0011_alter_anime_studio_3d'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='season',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='anime',
            name='studio',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='anime',
            name='studio_3D',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
