# Generated by Django 5.2.1 on 2025-05-13 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0012_alter_anime_season_alter_anime_studio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='slug',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
