# Generated by Django 5.2.1 on 2025-05-14 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0013_anime_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_title', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('seinen', 'Seinen'), ('shojo', 'Shojo'), ('shonen', 'Shonen'), ('yuri', 'Yuri')], max_length=50)),
                ('synopsis', models.TextField()),
                ('year_start_fr', models.CharField(max_length=4)),
                ('year_start_js', models.CharField(max_length=4)),
                ('author', models.CharField(blank=True, max_length=150, null=True)),
                ('scenariste', models.CharField(blank=True, max_length=150, null=True)),
                ('designer', models.CharField(blank=True, max_length=150, null=True)),
                ('chara_designer', models.CharField(blank=True, max_length=150, null=True)),
                ('storage', models.CharField(max_length=50)),
                ('url_nautiljon', models.TextField()),
                ('url_mal', models.TextField()),
                ('slug', models.CharField(max_length=255)),
            ],
        ),
    ]
