# Generated by Django 5.2.1 on 2025-05-14 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0014_manga'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='genres',
            field=models.ManyToManyField(related_name='mangas', to='collection.genre'),
        ),
        migrations.AddField(
            model_name='manga',
            name='themes',
            field=models.ManyToManyField(related_name='mangas', to='collection.theme'),
        ),
        migrations.AlterUniqueTogether(
            name='relationanime',
            unique_together={('anime_source', 'anime_target')},
        ),
        migrations.CreateModel(
            name='MangaImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='manga_images/')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('manga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='collection.manga')),
            ],
        ),
        migrations.CreateModel(
            name='MangaTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('language_code', models.CharField(choices=[('jp', 'jp'), ('en', 'en'), ('fr', 'fr'), ('ch', 'ch')], max_length=2)),
                ('is_original', models.BooleanField(default=False)),
                ('is_nickname', models.BooleanField(default=False)),
                ('is_main', models.BooleanField(default=False)),
                ('slug', models.CharField(max_length=255)),
                ('manga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manga_titles', to='collection.manga')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('manga', 'title', 'language_code'), name='unique_manga_title_language')],
            },
        ),
        migrations.CreateModel(
            name='RelationManga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(choices=[('suite', 'Suite'), ('prequel', 'Préquelle'), ('spin-off', 'Spin-off'), ('remake', 'Remake'), ('histoire-supplémentaire', 'Histoire supplémentaire'), ('version-alternative', 'Version alternative'), ('compilation', 'Compilation'), ('parodie', 'Parodie'), ('pilote', 'Pilote')], max_length=50)),
                ('manga_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations_as_source', to='collection.manga')),
                ('manga_target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations_as_target', to='collection.manga')),
            ],
            options={
                'unique_together': {('manga_source', 'manga_target')},
            },
        ),
    ]
