# Generated by Django 5.2.1 on 2025-05-14 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0015_manga_genres_manga_themes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.CharField(max_length=50)),
            ],
        ),
    ]
