# Generated by Django 5.2.1 on 2025-05-14 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0016_publisher'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='publisher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mangas', to='collection.publisher'),
        ),
    ]
