# Generated by Django 5.2.1 on 2025-05-14 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0017_manga_publisher'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeManga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='manga',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mangas', to='collection.typemanga'),
        ),
    ]
