# Generated by Django 5.2.1 on 2025-05-14 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0018_typemanga_alter_manga_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('native_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='animetitle',
            name='unique_anime_title_language',
        ),
        migrations.RemoveConstraint(
            model_name='mangatitle',
            name='unique_manga_title_language',
        ),
        migrations.RemoveField(
            model_name='animetitle',
            name='language_code',
        ),
        migrations.RemoveField(
            model_name='mangatitle',
            name='language_code',
        ),
        migrations.AddField(
            model_name='animetitle',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='collection.language'),
        ),
        migrations.AddField(
            model_name='mangatitle',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='collection.language'),
        ),
        migrations.AddConstraint(
            model_name='animetitle',
            constraint=models.UniqueConstraint(fields=('anime', 'title', 'language'), name='unique_anime_title_language'),
        ),
        migrations.AddConstraint(
            model_name='mangatitle',
            constraint=models.UniqueConstraint(fields=('manga', 'title', 'language'), name='unique_manga_title_language'),
        ),
    ]
