# Generated by Django 5.2.1 on 2025-05-14 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0021_format_origin_alter_anime_format_alter_anime_origin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='year_start_fr',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='manga',
            name='year_start_js',
            field=models.PositiveIntegerField(),
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(choices=[('winter', 'Hiver'), ('spring', 'Printemps'), ('summer', 'Été'), ('autumn', 'Automne')], max_length=10)),
                ('year', models.PositiveIntegerField()),
                ('slug', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'unique_together': {('season', 'year')},
            },
        ),
    ]
