# Generated by Django 5.2.1 on 2025-05-14 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0022_alter_manga_year_start_fr_alter_manga_year_start_js_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manga',
            old_name='year_start_js',
            new_name='year_start_jp',
        ),
    ]
