# Generated by Django 5.2.1 on 2025-05-15 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0024_people_role_remove_manga_author_contribution_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='chara_designer',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
