# Generated by Django 5.2.1 on 2025-05-15 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0025_alter_manga_chara_designer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='author',
            field=models.ManyToManyField(related_name='author', to='collection.contribution'),
        ),
        migrations.AlterField(
            model_name='manga',
            name='chara_designer',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
