# Generated by Django 5.2.1 on 2025-05-15 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0026_alter_manga_author_alter_manga_chara_designer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='author',
            field=models.ManyToManyField(blank=True, related_name='author', to='collection.contribution'),
        ),
        migrations.RemoveField(
            model_name='manga',
            name='chara_designer',
        ),
        migrations.RemoveField(
            model_name='manga',
            name='designer',
        ),
        migrations.AlterField(
            model_name='manga',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='mangas', to='collection.genre'),
        ),
        migrations.RemoveField(
            model_name='manga',
            name='scenariste',
        ),
        migrations.AlterField(
            model_name='manga',
            name='themes',
            field=models.ManyToManyField(blank=True, related_name='mangas', to='collection.theme'),
        ),
        migrations.AddField(
            model_name='manga',
            name='chara_designer',
            field=models.ManyToManyField(blank=True, related_name='chara_designer', to='collection.contribution'),
        ),
        migrations.AddField(
            model_name='manga',
            name='designer',
            field=models.ManyToManyField(blank=True, related_name='designer', to='collection.contribution'),
        ),
        migrations.AddField(
            model_name='manga',
            name='scenariste',
            field=models.ManyToManyField(blank=True, related_name='scenariste', to='collection.contribution'),
        ),
    ]
