# Generated by Django 5.2.1 on 2025-05-15 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0027_alter_manga_author_remove_manga_chara_designer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='StudioRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('label', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='anime',
            name='format',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anime', to='collection.format'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='genres',
            field=models.ManyToManyField(related_name='anime', to='collection.genre'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='origin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anime', to='collection.origin'),
        ),
        migrations.RemoveField(
            model_name='anime',
            name='studio',
        ),
        migrations.RemoveField(
            model_name='anime',
            name='studio_3D',
        ),
        migrations.AlterField(
            model_name='anime',
            name='themes',
            field=models.ManyToManyField(related_name='anime', to='collection.theme'),
        ),
        migrations.AlterField(
            model_name='animeimage',
            name='anime',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animeImage', to='collection.anime'),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='people',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contribution', to='collection.people'),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contribution', to='collection.role'),
        ),
        migrations.CreateModel(
            name='ContributionStudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributionStudio', to='collection.studio')),
                ('studioRole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributionStudio', to='collection.studiorole')),
            ],
        ),
        migrations.AddField(
            model_name='anime',
            name='studio',
            field=models.ManyToManyField(blank=True, related_name='anime_studio', to='collection.contributionstudio'),
        ),
        migrations.AddField(
            model_name='anime',
            name='studio_3D',
            field=models.ManyToManyField(blank=True, related_name='anime_studio3d', to='collection.contributionstudio'),
        ),
    ]
