# Generated by Django 5.2.1 on 2025-05-15 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0028_studio_studiorole_alter_anime_format_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='url_mal',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='anime',
            name='url_nautiljon',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='manga',
            name='url_mal',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='manga',
            name='url_nautiljon',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
