# Generated by Django 5.2.1 on 2025-05-15 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0029_alter_anime_url_mal_alter_anime_url_nautiljon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='origin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anime', to='collection.origin'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anime', to='collection.season'),
        ),
    ]
