# Generated by Django 5.2.1 on 2025-05-15 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0030_alter_anime_origin_alter_anime_season'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animetitle',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='mangatitle',
            name='slug',
        ),
        migrations.AlterField(
            model_name='anime',
            name='duration',
            field=models.IntegerField(blank=True, help_text='Durée moyenne d’un épisode en minutes', null=True),
        ),
        migrations.AlterField(
            model_name='anime',
            name='episode',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='anime',
            name='format',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anime', to='collection.format'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='main_title',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='anime',
            name='slug',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='genre',
            name='slug',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='language',
            name='native_name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='origin',
            name='label',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='people',
            name='slug',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='slug',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='relationtype',
            name='label',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='role',
            name='label',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='studio',
            name='slug',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='studiorole',
            name='label',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='theme',
            name='slug',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='typemanga',
            name='slug',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='AnimeEpisode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('titre', models.CharField(max_length=255)),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anime_episode', to='collection.anime')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('anime', 'number'), name='unique__episode_number')],
            },
        ),
    ]
