# Generated by Django 5.2.1 on 2025-05-15 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0031_remove_animetitle_slug_remove_mangatitle_slug_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animeepisode',
            old_name='titre',
            new_name='title',
        ),
    ]
