# Generated by Django 5.2.1 on 2025-05-15 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0032_rename_titre_animeepisode_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='TomeManga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('date_publication_jp', models.DateField(blank=True, null=True)),
                ('date_publication_fr', models.DateField(blank=True, null=True)),
                ('back_cover', models.TextField()),
                ('manga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tomes', to='collection.manga')),
            ],
            options={
                'ordering': ['manga', 'number'],
                'unique_together': {('manga', 'number')},
            },
        ),
    ]
