# Generated by Django 5.2.1 on 2025-05-15 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0033_tomemanga'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tomemanga',
            options={},
        ),
        migrations.AddField(
            model_name='tomemanga',
            name='slug',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='ChapterManga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('tome_manga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='collection.tomemanga')),
            ],
            options={
                'unique_together': {('tome_manga', 'number')},
            },
        ),
    ]
