# Generated by Django 5.2.1 on 2025-05-15 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0034_alter_tomemanga_options_tomemanga_slug_chaptermanga'),
    ]

    operations = [
        migrations.CreateModel(
            name='TomeMangaImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='manga_images/')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('tome_manga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='collection.tomemanga')),
            ],
        ),
    ]
