# Generated by Django 5.2.1 on 2025-05-16 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0035_tomemangaimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='anime', to='collection.genre'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='themes',
            field=models.ManyToManyField(blank=True, related_name='anime', to='collection.theme'),
        ),
        migrations.AlterField(
            model_name='animetitle',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='collection.language'),
        ),
        migrations.AlterField(
            model_name='manga',
            name='author',
            field=models.ManyToManyField(blank=True, related_name='mangas_author', to='collection.contribution'),
        ),
        migrations.AlterField(
            model_name='manga',
            name='chara_designer',
            field=models.ManyToManyField(blank=True, related_name='mangas_chara_designer', to='collection.contribution'),
        ),
        migrations.AlterField(
            model_name='manga',
            name='designer',
            field=models.ManyToManyField(blank=True, related_name='mangas_designer', to='collection.contribution'),
        ),
        migrations.AlterField(
            model_name='manga',
            name='main_title',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='manga',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mangas', to='collection.publisher'),
        ),
        migrations.AlterField(
            model_name='manga',
            name='scenariste',
            field=models.ManyToManyField(blank=True, related_name='mangas_scenariste', to='collection.contribution'),
        ),
        migrations.AlterField(
            model_name='manga',
            name='slug',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='manga',
            name='storage',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='manga',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mangas', to='collection.typemanga'),
        ),
        migrations.AlterField(
            model_name='mangatitle',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='collection.language'),
        ),
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_title', models.CharField(max_length=255, unique=True)),
                ('synopsis', models.TextField()),
                ('year_start_jp', models.PositiveIntegerField()),
                ('url_nautiljon', models.URLField(blank=True, max_length=500)),
                ('url_mal', models.URLField(blank=True, max_length=500)),
                ('slug', models.CharField(max_length=255, unique=True)),
                ('author', models.ManyToManyField(blank=True, related_name='scan_author', to='collection.contribution')),
                ('chara_designer', models.ManyToManyField(blank=True, related_name='scan_chara_designer', to='collection.contribution')),
                ('designer', models.ManyToManyField(blank=True, related_name='scan_designer', to='collection.contribution')),
                ('genres', models.ManyToManyField(blank=True, related_name='scan', to='collection.genre')),
                ('scenariste', models.ManyToManyField(blank=True, related_name='scan_scenariste', to='collection.contribution')),
                ('themes', models.ManyToManyField(blank=True, related_name='scan', to='collection.theme')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan', to='collection.typemanga')),
            ],
        ),
        migrations.CreateModel(
            name='ScanImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='scan_images/')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='collection.scan')),
            ],
        ),
        migrations.CreateModel(
            name='TomeScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('date_publication_jp', models.DateField(blank=True, null=True)),
                ('back_cover', models.TextField(null=True)),
                ('slug', models.CharField(max_length=255, null=True)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tomes', to='collection.scan')),
            ],
            options={
                'unique_together': {('scan', 'number')},
            },
        ),
        migrations.CreateModel(
            name='TomeScanImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='scan_images/')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('tome_scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='collection.tomescan')),
            ],
        ),
        migrations.CreateModel(
            name='RelationScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collection.relationtype')),
                ('scan_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations_as_source', to='collection.scan')),
                ('scan_target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations_as_target', to='collection.scan')),
            ],
            options={
                'unique_together': {('scan_source', 'scan_target')},
            },
        ),
        migrations.CreateModel(
            name='ScanTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('is_original', models.BooleanField(default=False)),
                ('is_nickname', models.BooleanField(default=False)),
                ('is_main', models.BooleanField(default=False)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='collection.language')),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_titles', to='collection.scan')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('scan', 'title', 'language'), name='unique_scan_title_language')],
            },
        ),
        migrations.CreateModel(
            name='ChapterScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('tome_scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_chapters', to='collection.tomescan')),
            ],
            options={
                'unique_together': {('tome_scan', 'number')},
            },
        ),
    ]
