# Generated by Django 5.2.1 on 2025-05-16 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0036_alter_anime_genres_alter_anime_themes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelationAnimeManga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('anime', 'Anime'), ('manga', 'Manga')], max_length=10)),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations_as_anime_manga', to='collection.anime')),
                ('manga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations_as_anime_manga', to='collection.manga')),
                ('relation_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collection.relationtype')),
            ],
            options={
                'unique_together': {('anime', 'manga', 'source_type')},
            },
        ),
        migrations.CreateModel(
            name='RelationAnimeScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('anime', 'Anime'), ('scan', 'Scan')], max_length=10)),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations_as_anime_scan', to='collection.anime')),
                ('relation_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collection.relationtype')),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations_as_anime_scan', to='collection.scan')),
            ],
            options={
                'unique_together': {('anime', 'scan', 'source_type')},
            },
        ),
        migrations.CreateModel(
            name='RelationMangaScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('manga', 'Manga'), ('scan', 'Scan')], max_length=10)),
                ('manga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations_as_manga_scan', to='collection.manga')),
                ('relation_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collection.relationtype')),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations_as_manga_scan', to='collection.scan')),
            ],
            options={
                'unique_together': {('manga', 'scan', 'source_type')},
            },
        ),
    ]
