# Generated by Django 5.2.1 on 2025-05-19 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0038_status_manga_status_scan_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mangas', to='collection.status'),
        ),
        migrations.AlterField(
            model_name='scan',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan', to='collection.status'),
        ),
    ]
