# Generated by Django 5.2.1 on 2025-05-19 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0039_alter_manga_status_alter_scan_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='origin',
            old_name='code',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='origin',
            name='label',
        ),
        migrations.AddField(
            model_name='origin',
            name='slug',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
