# Generated by Django 5.2.1 on 2025-05-19 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0041_rename_code_origin_name_remove_origin_label_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='origin',
            name='slug',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
