# Generated by Django 5.2.1 on 2025-05-19 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0042_alter_origin_slug'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contributionstudio',
            unique_together={('studio', 'studioRole')},
        ),
    ]
