# Generated by Django 5.2.1 on 2025-05-20 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0043_alter_contributionstudio_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='illustrator',
            field=models.ManyToManyField(blank=True, related_name='mangas_illustrator', to='collection.contribution'),
        ),
        migrations.AddField(
            model_name='scan',
            name='illustrator',
            field=models.ManyToManyField(blank=True, related_name='scan_illustrator', to='collection.contribution'),
        ),
    ]
