# Generated by Django 5.2.1 on 2025-05-20 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0044_manga_illustrator_scan_illustrator'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChapterManga',
            new_name='MangaChapter',
        ),
        migrations.RenameModel(
            old_name='TomeManga',
            new_name='MangaTome',
        ),
        migrations.RenameModel(
            old_name='TomeMangaImage',
            new_name='MangaTomeImage',
        ),
        migrations.RenameModel(
            old_name='TomeScan',
            new_name='ScanTome',
        ),
        migrations.RenameModel(
            old_name='TomeScanImage',
            new_name='ScanTomeImage',
        ),
        migrations.RenameModel(
            old_name='ChapterScan',
            new_name='TomeChapter',
        ),
    ]
