# Generated by Django 5.2.1 on 2025-05-20 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0046_rename_chaptermanga_mangachapter_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TomeChapter',
            new_name='ScanChapter',
        ),
    ]
