# Generated by Django 5.2.1 on 2025-05-20 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0047_rename_tomechapter_scanchapter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scantome',
            name='slug',
            field=models.CharField(max_length=255),
        ),
    ]
