# Generated by Django 5.2.1 on 2025-05-20 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0048_alter_scantome_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scan',
            old_name='year_start_jp',
            new_name='year_start',
        ),
        migrations.RenameField(
            model_name='scantome',
            old_name='date_publication_jp',
            new_name='date_publication',
        ),
    ]
